package com.emoto.protocol.fields;

public enum ChargerFaultCode {
	NO_FAULT,
	INSULATION_FAULT,
	CCS_COMM_FAULT,
	BMS_COMM_FAULT,
	GUN_UNLINKED,
	ESB_PUSHED,
	SYS_FAN_FAULT,
	CHARGER_FAULT_MAX,
	VOLTAGE_UNNORMAL,
	CURRENT_UNNORMAL,
	CONNECTOR_UNPLUGGED,
	CONTACT_FAULT,
	EMERGENT_STOP_FAULT,
	NO_CURRENT_AFTER_CONTACT
}
